language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
before_install: ./CI/travis.before_install.sh
install: ./CI/travis.install.sh
before_script:
  - mkdir build
  - cd src
script:
  - qmake && make -j2
  - cd ../build
  - cmake ..
  - make -j2
matrix:
  allow_failures:
    - os: osx
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ed233d9013d611a1568
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
