language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update
  - git clone https://github.com/lloyd/yajl.git
  - wget http://www.cmake.org/files/v3.0/cmake-3.0.0.tar.gz
  - tar -zxvf cmake-3.0.0.tar.gz
install:
  - sudo apt-get install build-essential qtbase5-dev qt5-default qtmultimedia5-dev qttools5-dev libhunspell-dev lua5.1 liblua5.1-0-dev libpcre3-dev libboost-dev zlib1g-dbg zlib1g-dev libzip-dev libpulse-dev
  - cd cmake-3.0.0
  - ./configure
  - sudo make install
  - cd ..
  - cd yajl
  - ./configure
  - sudo make install
  - cd ..
before_script:
  - mkdir build
  - cd src
script:
  - qmake && make -j2
  - cd ../build
  - cmake ..
  - make -j2
